# -*- coding: utf-8 -*-
"""Actividad 23/02/2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vTXc1RAN-U991QUnzawPAAIJXYKvbWDl

# 📊 Análisis de Datos - Sector Minero Energético Colombia
## EDA + ETL + Consultas SQL con Pandas

---

### 📋 Objetivos del Notebook

1. *Cargar datos* desde la base de datos SQLite a Pandas DataFrames
2. **Explorar los datos** (`EDA`) - entender estructura y calidad
3. _**Transformar los datos**_ (`ETL`) - limpiar y preparar
4. **Ejecutar consultas SQL** - practicar las 9 consultas del taller
>5. **Visualizar resultados** - gráficos para mejor comprensión

---

## 📚 PASO 1: Importar Librerías Necesarias

Importamos las librerías que vamos a usar para trabajar con datos.
"""

# ============================================
# IMPORTAR LIBRERÍAS
# ============================================

# Pandas para manejar datos tabulares (DataFrames)
import pandas as pd

# SQLite para conectar a la base de datos
import sqlite3

# Matplotlib y Seaborn para gráficos
import matplotlib.pyplot as plt
import seaborn as sns
# NumPy para operaciones numéricas
import numpy as np

# Configuración para ver todas las columnas
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

# Mensaje de confirmación
print("Todo OK")

"""## 📚 PASO 2: Conectar a la Base de Datos

Nos conectamos a la base de datos SQLite para poder leer los datos.
"""

# ============================================
# CONEXIÓN A LA BASE DE DATOS
# ============================================

# Nombre del archivo de la base de datos
db_name = "all_seasons.csv"

# Conectar a la base de datos
conn = sqlite3.connect(db_name)

# Asegurar que las tablas existan ejecutando el script SQL
try:
  with open("SectorMineroEnergeticoColombia.sql", "r") as f:
    sql_scrip = f.read()
  conn.executescript(sql_scrip)
  print("✅Se ejecuta correctamente")
except Exception as e:
  print("Error al ejecutar SQL")
# --------------------------------------------------------

# Verificar conexión
print(f"✅ Conexión a la base de datos establecida a: {db_name}")

"""## 📚 PASO 3: Ver Tablas Disponibles

Vamos a ver qué tablas tiene nuestra base de datos.
"""

# ============================================
# VER TABLAS DISPONIBLES
# ============================================

# Consulta para ver todas las tablas
query_tablas = "SELECT name FROM sqlite_master WHERE type= 'table';"

# Ejecutar consulta y cargar en DataFrame
df_tablas = pd.read_sql_query(query_tablas, conn)

# Mostrar tablas
print("✅ Tablas disponibles:")
df_tablas

"""## 📚 PASO 4: Cargar Datos a DataFrames (ETL - Extract)

Cargamos cada tabla importante a un DataFrame de pandas para trabajar con ellas.
"""

# ============================================
# CARGAR DATOS A DATAFRAMES
# ============================================

# Cargar tabla de proyectos
df_proyectos = pd.read_sql_query("SELECT * FROM proyectos", conn)

# Cargar tabla de tipos_energia
df_tipos_energia = pd.read_sql_query("SELECT * FROM tipos_energia", conn)

# Cargar tabla de inversiones
df_inversiones = pd.read_sql_query("SELECT * FROM inversiones", conn)

# Cargar tabla de empresas
df_empresas = pd.read_sql_query("SELECT * FROM empresas", conn)


# Mensaje de confirmación
print("✅ Datos cargados correctamente a DataFrames")
df_empresas.shape

"""## 📊 PASO 5: EDA - Exploración Inicial de Datos

Vamos a explorar los datos para entender su estructura y calidad.

### 5.1 Ver Primeras Filas de Cada Tabla
"""

# ============================================
# VER PRIMERAS FILAS PROYECTOS
# ============================================
df_proyectos.head()

"""### 5.2 Ver Información de las Tablas"""

# ============================================
# INFORMACIÓN DE LAS TABLAS PROYECTOS
# ============================================

df_proyectos.info()

# Mostrar los ultimos 5
df_proyectos.tail()

# Mostrar el Orden
df_proyectos.shape

"""### 5.3 Verificar Valores Faltantes"""

# ============================================
# VERIFICAR VALORES FALTANTES
# ============================================

print("🔍 VALORES FALTANTES - PROYECTOS")
print(df_proyectos.isnull().sum())


print("\n🔍 VALORES FALTANTES - TIPOS DE ENERGÍA")
print(df_tipos_energia.isnull().sum())

"""### 5.4 Estadísticas Descriptivas"""

# ============================================
# ESTADÍSTICAS DESCRIPTIVAS PROYECTOS
# ============================================

df_proyectos.describe()

"""# PASO 5.5: Crear DataFrame Consolidado (Tipo Data Warehouse)"""

# Info Inversiones
df_inversiones.info()

# ============================================
# PASO 5.5: Crear DataFrame Consolidado (Tipo Data Warehouse)
# ============================================

print("🔄 Creando DataFrame consolidado con información de todas las tablas...")

# Unir df_proyectos con df_tipos_energia
df_consolidado = pd.merge(df_proyectos,
                          df_tipos_energia,
                          left_on='tipo_energia',
                          right_on='id_tipo',
                          how='left')

# Unir el resultado con df_inversiones
df_consolidado = pd.merge(df_consolidado,
                          df_inversiones,
                          left_on='id_proyecto',
                          right_on='proyecto_id',
                          how='left',
                          suffixes=('_proyecto', '_inversion'))

# Unir el resultado con df_empresas
df_consolidado = pd.merge(df_consolidado,
                          df_empresas,
                          left_on='id_proyecto',
                          right_on='proyecto_id',
                          how='left',
                          suffixes=('_consolidado', '_empresa'))

# Limpiar y renombrar columnas duplicadas o con sufijos
df_consolidado = df_consolidado.drop(columns={
    'nombre_consolidado': 'nombre_proyecto',
    'nombre_empresa': 'nombre_empresa_asociada',
    'tipo': 'tipo_energia_descripción',
    'monto': 'monto_inversion',
    'descripcion': 'descripción_proyecto'
})

# Eliminar columnas redundantes si existen después de los merges (ej. ids duplicados)
df_consolidado = df_consolidado.drop(columns=[
    'id_tipo','proyecto_id_inversion','proyecto_id_empresa'
    ],errors='ignore')

print("✅ DataFrame consolidado creado exitosamente.")
print("📊 Primeras 5 filas del DataFrame consolidado:")
df_consolidado.head()

print("📊 Información del DataFrame consolidado:")
df_consolidado.info()

"""## 🔄 PASO 6: ETL - Transformación de Datos

Ahora vamos a transformar y limpiar los datos si es necesario.
"""

# ============================================
# TRANSFORMACIÓN DE DATOS
# ============================================

# 1. Renombrar columnas para mayor claridad

# 2. Crear columna con el año (si existe fecha)

# 3. Calcular estadísticas de inversión por proyecto

# Renombrar columnas del resumen

print("✅ Transformaciones completadas:")
print(f"   - Columnas renombradas en proyectos")
print(f"   - Resumen de inversiones creado")
print(f"\n📊 Resumen de Inversiones:")

"""## 🔍 PASO 7: EJECUTAR CONSULTAS SQL DEL TALLER

Ahora vamos a ejecutar las 9 consultas del taller usando pandas.

### Consulta 1: Todos los tipos de energía
"""

# ============================================
# CONSULTA 1: Todos los tipos de energía
# ============================================

print("📋 CONSULTA 1: Todos los tipos de energía")


# Método 1: Usando el DataFrame ya cargado


# Mostrar resultados


print(f"\n✅ Total de tipos de energía: {len(consulta_1)}")

"""### Consulta 2: Nombre y ubicación de proyectos con tipo de energía ID 2"""

# ============================================
# CONSULTA 2: Proyectos con tipo de energía ID 2
# ============================================

print("📋 CONSULTA 2: Nombre y ubicación de proyectos (tipo energía ID 2)")


# Filtrar proyectos donde tipo_energia = 2


# Mostrar resultados


print(f"\n✅ Total de proyectos con tipo de energía ID 2: {len(consulta_2)}")

"""### Consulta 3: Todos los proyectos"""

# ============================================
# CONSULTA 3: Todos los proyectos
# ============================================

print("📋 CONSULTA 3: Todos los proyectos")


# Usar el DataFrame completo


# Mostrar resultados


print(f"\n✅ Total de proyectos: {len(consulta_3)}")

"""### Consulta 4: Suma total de inversión por proyecto"""

# ============================================
# CONSULTA 4: Suma total de inversión por proyecto
# ============================================

print("📋 CONSULTA 4: Suma total de inversión por proyecto")


# Agrupar por proyecto_id y sumar el monto


# Mostrar resultados


print(f"\n✅ Total de proyectos con inversión: {len(consulta_4)}")

"""### Consulta 5: Proyecto, empresa asociada y monto de inversión"""

# ============================================
# CONSULTA 5: Proyecto, empresa y monto de inversión
# ============================================

print("📋 CONSULTA 5: Proyecto, empresa asociada y monto de inversión")


# Hacer JOIN entre las 3 tablas
# Corregido: Usar 'left_on' y 'right_on' para unir df_proyectos y df_empresas

# Seleccionar columnas específicas

# Mostrar resultados

print(f"\n✅ Total de registros: {len(consulta_5)}")

"""### Consulta 6: Cada proyecto con su tipo de energía (JOIN)"""

# ============================================
# CONSULTA 6: Proyecto con su tipo de energía (JOIN)
# ============================================

print("📋 CONSULTA 6: Cada proyecto con su tipo de energía")


# Hacer JOIN entre proyectos y tipos_energia


# Seleccionar columnas específicas
# Corregido: 'nombre' en lugar de 'nombre_x' ya que no hay conflicto de nombres.

# Mostrar resultados

print(f"\n✅ Total de proyectos con tipo de energía: {len(consulta_6)}")

"""### Consulta 7: Nombre del proyecto y su tipo de energía"""

# ============================================
# CONSULTA 7: Nombre del proyecto y tipo de energía
# ============================================

print("📋 CONSULTA 7: Nombre del proyecto y su tipo de energía")


# Hacer JOIN (similar a consulta 6)


# Seleccionar columnas específicas
# Corregido: 'nombre' en lugar de 'nombre_x' y 'tipo' en lugar de 'nombre_tipo'

# Mostrar resultados

print(f"\n✅ Total de registros: {len(consulta_7)}")

"""### Consulta 8: Describir tablas (estructura)"""

# ============================================
# CONSULTA 8: Describir estructura de tablas
# ============================================

print("📋 CONSULTA 8: Estructura de las tablas")


print("\n📊 ESTRUCTURA - tipos_energia:")

print("\n📊 ESTRUCTURA - proyectos:")

"""### Consulta 9: Dos consultas propuestas

## 📊 PASO 8: Visualización de Datos

Vamos a crear algunos gráficos para entender mejor los datos.

## 📝 PASO 9: Resumen Final

Vamos a crear un resumen de todo lo que hicimos.
"""

# ============================================
# RESUMEN FINAL
# ============================================

"""## 📚 PASO 10: Cerrar Conexión

Es importante cerrar la conexión a la base de datos cuando terminamos.
"""

# ============================================
# CERRAR CONEXIÓN
# ============================================

# Cerrar conexión a la base de datos


print("✅ Conexión a la base de datos cerrada correctamente")

"""# Task CREADO CON IA
 Create four visualizations using `df_consolidado`: 1) a bar chart for total investment by energy type, 2) a bar chart for project count by company industry, 3) a histogram/density plot for investment amount distribution, and 4) a heatmap for numerical column correlations. Finally, summarize the insights from these visualizations.

## Gráfico 1: Inversión Total por Tipo de Energía

### Subtask:
Crear un gráfico de barras para mostrar la suma total de inversión para cada tipo de energía. Utilizará las columnas 'tipo_energia_descripcion' y 'monto_inversion' del `df_consolidado`.

**Reasoning**:
The user wants to create a bar chart that displays the total investment for each energy type. I need to group the `df_consolidado` by 'tipo_energia_descripcion' and sum the 'monto_inversion' to get the data for the chart, then plot it with appropriate labels and title.
"""

# ============================================
# GRÁFICO 1: Inversión Total por Tipo de Energía
# ============================================

plt.figure(figsize=(12, 7))

# Agrupar por tipo de energía y sumar el monto de inversión
inversion_por_tipo = df_consolidado.groupby('tipo_energia_descripcion')['monto_inversion'].sum().sort_values(ascending=False)

# Crear gráfico de barras
sns.barplot(x=inversion_por_tipo.index, y=inversion_por_tipo.values, palette='viridis')

# Añadir títulos y etiquetas
plt.title('Inversión Total por Tipo de Energía', fontsize=16, fontweight='bold')
plt.xlabel('Tipo de Energía', fontsize=12)
plt.ylabel('Monto Total de Inversión', fontsize=12)
plt.xticks(rotation=45, ha='right') # Rotar etiquetas para mejor legibilidad
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Añadir valores en las barras
for index, value in enumerate(inversion_por_tipo.values):
    plt.text(index, value + 100000, f'${value:,.0f}', ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

print("✅ Gráfico 1 generado: Inversión Total por Tipo de Energía")

"""**Reasoning**:
The previous `sns.barplot` call raised a FutureWarning about passing `palette` without `hue`. To fix this, I will explicitly assign the `x` variable to `hue` and set `legend=False` as suggested by the warning message.


"""

# ============================================
# GRÁFICO 1: Inversión Total por Tipo de Energía
# ============================================

plt.figure(figsize=(12, 7))

# Agrupar por tipo de energía y sumar el monto de inversión
inversion_por_tipo = df_consolidado.groupby('tipo_energia_descripcion')['monto_inversion'].sum().sort_values(ascending=False)

# Crear gráfico de barras, aplicando el fix for FutureWarning
sns.barplot(x=inversion_por_tipo.index, y=inversion_por_tipo.values, palette='viridis', hue=inversion_por_tipo.index, legend=False)

# Añadir títulos y etiquetas
plt.title('Inversión Total por Tipo de Energía', fontsize=16, fontweight='bold')
plt.xlabel('Tipo de Energía', fontsize=12)
plt.ylabel('Monto Total de Inversión', fontsize=12)
plt.xticks(rotation=45, ha='right') # Rotar etiquetas para mejor legibilidad
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Añadir valores en las barras
for index, value in enumerate(inversion_por_tipo.values):
    plt.text(index, value + 100000, f'${value:,.0f}', ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

print("✅ Gráfico 1 generado: Inversión Total por Tipo de Energía")

"""## Gráfico 2: Conteo de Proyectos por Industria de la Empresa

### Subtask:
Crear un gráfico de barras para mostrar el número de proyectos asociados a cada industria de empresa. Utilizará la columna 'industria' del `df_consolidado` y contará la ocurrencia de 'id_proyecto' para cada industria.

**Reasoning**:
I need to generate Python code to create a bar chart that displays the count of projects per company industry. This involves grouping the `df_consolidado` by the 'industria' column and counting the unique 'id_proyecto' for each industry.
"""

# ============================================
# GRÁFICO 2: Conteo de Proyectos por Industria de la Empresa
# ============================================

plt.figure(figsize=(12, 7))

# Agrupar por industria y contar proyectos únicos
proyectos_por_industria = df_consolidado.groupby('industria')['id_proyecto'].nunique().sort_values(ascending=False)

# Crear gráfico de barras
sns.barplot(x=proyectos_por_industria.index, y=proyectos_por_industria.values, palette='plasma', hue=proyectos_por_industria.index, legend=False)

# Añadir títulos y etiquetas
plt.title('Número de Proyectos por Industria de la Empresa', fontsize=16, fontweight='bold')
plt.xlabel('Industria', fontsize=12)
plt.ylabel('Número de Proyectos', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Añadir valores en las barras
for index, value in enumerate(proyectos_por_industria.values):
    plt.text(index, value + 0.1, str(value), ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

print("✅ Gráfico 2 generado: Número de Proyectos por Industria de la Empresa")

"""## Gráfico 3: Distribución del Monto de Inversión

### Subtask:
Crear un histograma o gráfico de densidad para visualizar la distribución del 'monto_inversion' en `df_consolidado`. Esto ayudará a entender la concentración de las inversiones.

**Reasoning**:
I need to generate Python code to create a histogram or density plot to visualize the distribution of 'monto_inversion' from the `df_consolidado` DataFrame. This will help in understanding the concentration of investments.
"""

# ============================================
# GRÁFICO 3: Distribución del Monto de Inversión
# ============================================

plt.figure(figsize=(12, 7))

# Crear histograma de la columna 'monto_inversion'
sns.histplot(df_consolidado['monto_inversion'], kde=True, bins=5, color='green', edgecolor='black')

# Añadir títulos y etiquetas
plt.title('Distribución del Monto de Inversión', fontsize=16, fontweight='bold')
plt.xlabel('Monto de Inversión', fontsize=12)
plt.ylabel('Frecuencia / Densidad', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

print("✅ Gráfico 3 generado: Distribución del Monto de Inversión")

"""## Gráfico 4: Heatmap de Correlación de Columnas Numéricas

### Subtask:
Crear un heatmap para visualizar la matriz de correlación entre las columnas numéricas de `df_consolidado`. Esto ayudará a identificar relaciones entre las variables cuantitativas.

## Gráfico 4: Heatmap de Correlación de Columnas Numéricas

### Subtask:
Crear un heatmap para visualizar la matriz de correlación entre las columnas numéricas de `df_consolidado`. Esto ayudará a identificar relaciones entre las variables cuantitativas.

**Reasoning**:
I need to generate Python code to create a heatmap showing the correlation matrix of numerical columns in `df_consolidado`. This involves selecting numeric columns, calculating their correlation, and then plotting it using `seaborn.heatmap`.
"""

# ============================================
# GRÁFICO 4: Heatmap de Correlación de Columnas Numéricas
# ============================================

plt.figure(figsize=(10, 8))

# Seleccionar solo las columnas numéricas del DataFrame consolidado
df_numeric = df_consolidado.select_dtypes(include=['number'])

# Calcular la matriz de correlación
correlation_matrix = df_numeric.corr()

# Crear el heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)

# Añadir título
plt.title('Heatmap de Correlación de Columnas Numéricas', fontsize=16, fontweight='bold')

plt.tight_layout()
plt.show()

print("✅ Gráfico 4 generado: Heatmap de Correlación de Columnas Numéricas")

"""## 📝 Resumen de Insights de las Visualizaciones

Con los gráficos generados, podemos extraer las siguientes conclusiones:

### Gráfico 1: Inversión Total por Tipo de Energía

- **Inversión Dominante**: Observamos que la energía Eólica es la que ha recibido la mayor inversión, seguida por la Geotérmica.
- **Diversificación**: Aunque Eólica domina, hay inversiones significativas en otros tipos de energía como Hidrógeno Verde, Biomasa y Solar, lo que indica una diversificación en el sector.

### Gráfico 2: Conteo de Proyectos por Industria de la Empresa

- **Distribución Equitativa**: Se observa que cada industria (Biomasa, Energía Eólica, Energía Solar, Geotermia, Hidrógeno Verde) tiene asociado un número similar de proyectos (en este caso, 1 proyecto por industria, lo que sugiere que cada proyecto puede ser único en su tipo de industria o que los datos son limitados para mostrar más diversidad).

### Gráfico 3: Distribución del Monto de Inversión

- **Asimetría en la Inversión**: La distribución muestra una concentración de proyectos en rangos de inversión más bajos, con algunos proyectos outliers que representan inversiones significativamente mayores (e.g., el proyecto eólico).
- **Identificación de Grandes Inversiones**: El histograma permite identificar rápidamente los rangos donde se encuentran la mayoría de las inversiones y dónde se ubican las inversiones de mayor cuantía.

### Gráfico 4: Heatmap de Correlación de Columnas Numéricas

- **Correlación Alta de IDs**: Es esperable una correlación perfecta (1.00) entre `id_proyecto`, `id_inversion`, `proyecto_id_consolidado` y `id_empresa`, ya que son IDs primarios o foráneos directamente relacionados que identifican las mismas entidades.
- **Correlación de Tipo de Energía**: La columna `tipo_energia` muestra correlaciones positivas con los IDs, lo que puede indicar una asociación en el orden de asignación de IDs o una relación implícita en la estructura de los datos.
- **Baja Correlación con Monto de Inversión**: El `monto_inversion` muestra una correlación muy baja o casi nula con la mayoría de los IDs y el tipo de energía, lo que sugiere que el tamaño de la inversión no está directamente dictado por el ID del proyecto o el tipo de energía en sí mismo, sino probablemente por otros factores no numéricos o por la naturaleza intrínseca de cada proyecto.

## 📝 Resumen de Insights de las Visualizaciones

Con los gráficos generados, podemos extraer las siguientes conclusiones:

### Gráfico 1: Inversión Total por Tipo de Energía

- **Inversión Dominante**: Observamos que la energía Eólica es la que ha recibido la mayor inversión, seguida por la Geotérmica.
- **Diversificación**: Aunque Eólica domina, hay inversiones significativas en otros tipos de energía como Hidrógeno Verde, Biomasa y Solar, lo que indica una diversificación en el sector.

### Gráfico 2: Conteo de Proyectos por Industria de la Empresa

- **Distribución Equitativa**: Se observa que cada industria (Biomasa, Energía Eólica, Energía Solar, Geotermia, Hidrógeno Verde) tiene asociado un número similar de proyectos (en este caso, 1 proyecto por industria, lo que sugiere que cada proyecto puede ser único en su tipo de industria o que los datos son limitados para mostrar más diversidad).

### Gráfico 3: Distribución del Monto de Inversión

- **Asimetría en la Inversión**: La distribución muestra una concentración de proyectos en rangos de inversión más bajos, con algunos proyectos outliers que representan inversiones significativamente mayores (e.g., el proyecto eólico).
- **Identificación de Grandes Inversiones**: El histograma permite identificar rápidamente los rangos donde se encuentran la mayoría de las inversiones y dónde se ubican las inversiones de mayor cuantía.

### Gráfico 4: Heatmap de Correlación de Columnas Numéricas

- **Correlación Alta de IDs**: Es esperable una correlación perfecta (1.00) entre `id_proyecto`, `id_inversion`, `proyecto_id_consolidado` y `id_empresa`, ya que son IDs primarios o foráneos directamente relacionados que identifican las mismas entidades.
- **Correlación de Tipo de Energía**: La columna `tipo_energia` muestra correlaciones positivas con los IDs, lo que puede indicar una asociación en el orden de asignación de IDs o una relación implícita en la estructura de los datos.
- **Baja Correlación con Monto de Inversión**: El `monto_inversion` muestra una correlación muy baja o casi nula con la mayoría de los IDs y el tipo de energía, lo que sugiere que el tamaño de la inversión no está directamente dictado por el ID del proyecto o el tipo de energía en sí mismo, sino probablemente por otros factores no numéricos o por la naturaleza intrínseca de cada proyecto.

## Finalizar Tarea

### Subtask:
Resumir los gráficos generados y las principales conclusiones obtenidas de la visualización de los datos del `df_consolidado`.

## Summary:

### Q&A
The task implicitly asked for a summary of insights from the generated visualizations. The key insights are detailed in the "Data Analysis Key Findings" section below.

### Data Analysis Key Findings
*   **Investment by Energy Type**: Wind energy received the highest total investment, followed by Geothermal energy. There is also significant investment diversification across Green Hydrogen, Biomass, and Solar energy types.
*   **Projects by Industry**: Each industry (Biomass, Wind Energy, Solar Energy, Geothermal, Green Hydrogen) is associated with a single project, which may indicate that each project is unique to its industry or points to a limited dataset.
*   **Investment Amount Distribution**: The distribution of investment amounts is asymmetrical, with a concentration of projects in the lower investment ranges. A few outlier projects represent significantly larger investments, such as the wind energy project.
*   **Numerical Column Correlations**: A strong positive correlation (1.00) exists among ID-related columns (`id_proyecto`, `id_inversion`, `proyecto_id_consolidado`, `id_empresa`), as expected for identifiers. However, the `monto_inversion` (investment amount) shows very low or negligible correlation with these IDs and `tipo_energia`, suggesting that investment size is influenced by factors beyond simple project or company identifiers.

### Insights or Next Steps
*   Further investigation into the factors driving the significant investment in wind and geothermal energy could reveal strategic priorities or market opportunities.
*   Given the low correlation between investment amount and project/company IDs, future analysis should focus on identifying other variables (e.g., project scale, technology readiness, policy incentives) that strongly influence investment size.
"""